### PR TITLE
Finished Wallet backup Screen

### PR DESCRIPTION
**Pull request by theafolayan**
**Task**:
Work on Wallet backup screen

**Task Type**:
 feature 

**Relevant Trello Card**:
[https://trello.com/c/82RdB5r0/17-work-on-back-up-wallet-screen](https://trello.com/c/82RdB5r0/17-work-on-back-up-wallet-screen)

**Task Description**:
Work on the back-up wallet screen. Refer to the screen labelled "Wallet backup" on the Figma design.

### CODE REVIEW

**Comment by theafolayan** [comment]
simulator_screenshot_EE846004-4ECA-4270-9E17-48F1B148FCC0

Simulator screenshot

**Review by humaidhusain98 — APPROVED** [review]
Looks good to me

**Review by kingsley-einstein — CHANGES_REQUESTED** [review]
@theafolayan Please merge changes and push again.

**Comment by theafolayan** [comment]
Changes merged and conflicts were fixed. kindly review :D

**Pull request merged**
