### PR TITLE
3 Tasks ( Settings Screen, Secret phrase Screen and Verify Secret Phrase screen)

### PR DESCRIPTION
**Pull request by theafolayan**
**Task**:
Work on Settings, SecretPhrase and verify secretphrase  Screens 

**Tasks Type**:
 feature 

**Relevant Trello Cards**:
> [https://trello.com/c/DdObnILc/19-work-on-settings-screen](https://trello.com/c/DdObnILc/19-work-on-settings-screen)
> [https://trello.com/c/ni7ylE0A/15-work-on-secret-phrase-screen](https://trello.com/c/ni7ylE0A/15-work-on-secret-phrase-screen)
> [https://trello.com/c/qVx9mIA0/16-work-on-verify-secret-phrase-screen](https://trello.com/c/qVx9mIA0/16-work-on-verify-secret-phrase-screen)

**Task Description**:
> Work on the  Settings screen. Refer to the screen labelled "Settings" on the Figma design.
> Work on the secret phrase screen. Use placeholders for the phrases. Refer to the screen labelled "secret phrase" on the Figma design.
> Work on the verify secret phrase screen. Use placeholders for the phrases. Refer to the screen labelled "Veriy Secret phrase" on the Figma design.

### CODE REVIEW

**Comment by theafolayan** [comment]
simulator_screenshot_EBAC29B6-2F0D-4524-AA63-D0C0435D4BEE
Screenshot on simulator

**Comment by theafolayan** [comment]
simulator_screenshot_8794A5F6-0410-424A-BE64-B84CA483EC0D
 View Secretphrase screenshot from simulator

**Comment by theafolayan** [comment]
simulator_screenshot_B1BC9DD2-362E-484A-91DD-17947E177372

Simulator screenshot for verify seed phrase screen

**Review by humaidhusain98 — CHANGES_REQUESTED** [review]
Instagram Logo is missing
InstaMissing
 
Also please make the Verify Secret Phrase more functional like when we click the selected word , please remove that word from  the existing List and add it to the user Selected list instead of just writing word

**Comment by theafolayan** [comment]
> 
The Instagram logo visibility issue has been fixed, thanks for pointing that out... It was because of a typo 😆 

I'll enable the proper functionality for updating the correct word later, my head is blank right now 🤣  If you could help with that, i'd be glad

**Review by kingsley-einstein — CHANGES_REQUESTED** [review]
@theafolayan Please fix merge conflicts.

**Comment by theafolayan** [comment]
> @theafolayan Please fix merge conflicts.

Fixed @kingsley-einstein 👍

**Review by humaidhusain98 — APPROVED** [review]
Hi @theafolayan I have implemented the proper functionality in the verifySeedPhrase Screen. @kingsley-einstein , @theafolayan  please check

**Comment by theafolayan** [comment]
You're awesome man @humaidhusain98 ! 😅

**Comment by humaidhusain98** [comment]
Thanks @theafolayan  :)

**Comment by humaidhusain98** [comment]
@theafolayan Sorry there is a problem in secretPhrase, I will fix it

**Comment by humaidhusain98** [comment]
@theafolayan  Please develop for Dark Mode as well
DarkModeNotImplemented
DarkModeNot

**Comment by theafolayan** [comment]
@humaidhusain98 please pull the recent change I made :)

**Comment by humaidhusain98** [comment]
The error has been fixed in the last commit @theafolayan . Please take a pull before you work on the Dark Mode

**Review by kingsley-einstein — APPROVED** [review]
Looks good to me!

**Pull request merged**
