### PR TITLE
2 Tasks (Create Legal and Passcode screens)

### PR DESCRIPTION
**Pull request by humaidhusain98**
Task:
2 Tasks (Create Legal Screen(Legal 1 and Legal 2) and PassCode Entry Screen(Passcode Entry 1 and Code Entry) )

Task Type:
feature

Relevant Trello Card:
https://trello.com/c/U1BN466j/13-create-legal-screen
https://trello.com/c/kqdZM6qp/14-create-passcode-entry-screen

Task Description:
Creating Both Legal and Passcode Entry Screen for both dark and light mode after pulling from master. Also Fixed the Status Bar Being fully black in dark Mode and created Button VButton2 for Dark and Light Mode UI as VButton does not work in dark Mode

### CODE REVIEW

**Comment by humaidhusain98** [comment]
Legal 1 Screen Screenshot
Legal1

Legal 2 Screen Screenshot
Legal2

**Review by theafolayan — APPROVED** [review]
I have a few suggestions maybe? 

The PolicyText component uses styles already declared in VText.js, All you need to do is pass the font name eg `<Vtext font-="GilroyMedium"> content </Vtext>  `

Also, for the forward and backward icons, we can use `<VIcon/>` and pass in `name ="chevron-back" `

Just so we don't have to write already existing components

**Comment by humaidhusain98** [comment]
@theafolayan Done implementing your suggestion but I cannot find the forward icon using VIcon component

**Comment by theafolayan** [comment]
@humaidhusain98 The VIcon component uses the ionicons library and you can see all available icon names here 
[https://ionic.io/ionicons](https://ionic.io/ionicons)  

All you need to do is to pass the icon name as a prop like this 
`<VIcon name="chevron-forward"/>`

**Review by kingsley-einstein — CHANGES_REQUESTED** [review]
@humaidhusain98 Please pull changes and fix conflict. Ensure you accept every incoming change.

**Review by theafolayan — APPROVED** [review]
Looks Good

**Review by kingsley-einstein — APPROVED** [review]
Looks good! Approved!

**Pull request merged**
