### PR TITLE
Ve fi wallet@kingsley

### PR DESCRIPTION
**Pull request by kingsley-einstein**
**Task**:
2 tasks completed (create reusable alert and set up linting)

**Task Type**:
chore & feature

**Relevant Trello Card**:
[https://trello.com/c/fHQHN5x2](https://trello.com/c/fHQHN5x2)
[https://trello.com/c/pleOMo76](https://trello.com/c/pleOMo76)

**Task Description**:
Bootstrapped linting configuration using the eslint CLI & created a reusable alert component by using `react-native-expo-fancy-alerts`.

### CODE REVIEW

**Review by theafolayan — APPROVED** [review]
Looks Okay to me!

**Review by humaidhusain98 — COMMENTED** [review]
Facing some problems in VText.js and colors.js as they do not match with  their data formats
Screenshot from 2022-05-03 00-32-55
Screenshot from 2022-05-03 00-35-08prob

**Comment by kingsley-einstein** [comment]
> Facing some problems in VText.js and colors.js as they do not match with their data formats Screenshot from 2022-05-03 00-32-55 Screenshot from 2022-05-03 00-35-08prob

Change has been made!

**Review by humaidhusain98 — COMMENTED** [review]
Please add "import * as colors from '../../constants/colors';" in Button.js as well instead of "import colors from '../../constants/colors';"
Screenshot from 2022-05-03 10-05-33

**Review by humaidhusain98 — APPROVED** [review]
Looks good to me

**Pull request merged**
